import { useEffect, useState, useRef, useCallback } from 'react';
import { useSearchParams } from 'react-router-dom';
import * as signalR from '@microsoft/signalr';

interface OverlayPosition {
    x: number;
    y: number;
    width: number;
    height: number;
    enabled: boolean;
}

interface OverlayCardConfig extends OverlayPosition {
    backgroundColor: string;
    borderRadius: number;
    borderColor: string;
    borderWidth: number;
    boxShadow: boolean;
    opacity: number;
}

interface OverlayMediaConfig extends OverlayPosition {
    id: string;
    url: string;
    fit: 'cover' | 'contain' | 'fill';
    animationIn: string;
    animationOut: string;
    animationDuration: number;
    zIndex: number;
    videoVolume: number;
    playVideoAudio: boolean;
}

interface OverlayTextConfig extends OverlayPosition {
    id: string;
    template: string;
    fontFamily: string;
    fontSize: number;
    fontWeight: string;
    color: string;
    textAlign: 'left' | 'center' | 'right';
    textShadow: boolean;
    animationIn: string;
    animationOut: string;
    animationDuration: number;
    zIndex: number;
}

interface OverlayConfig {
    canvas?: {
        width: number;
        height: number;
    };
    card?: OverlayCardConfig;
    media?: OverlayMediaConfig;
    texts?: OverlayTextConfig[];
    audio?: {
        url: string;
        volume: number;
        enabled: boolean;
    };
    duration?: number;
    animationIn?: string;
    animationOut?: string;
}

interface MediaConfig {
    enabled?: boolean;
    mode?: 'simple' | 'advanced';
    advanced?: {
        video?: { url?: string; volume?: number; loop?: boolean };
        audio?: { url?: string; volume?: number; loop?: boolean };
        image?: { url?: string };
    };
}

interface TipAlertData {
    tipId: number;
    donorName: string;
    amount: number;
    currency: string;
    message: string;
    processedMessage?: string;
    timeAdded: number;
    formattedAmount: string;
    tierName?: string;
    eventType?: string;

    // NEW: Flat fields (same structure as EventAlertData)
    soundUrl?: string;
    soundVolume?: number;
    mediaUrl?: string;
    mediaType?: string;
    playVideoAudio?: boolean;
    videoVolume?: number;
    videoMuted?: boolean;
    duration?: number;
    animationIn?: string;
    animationOut?: string;
    effects?: string[];
    overlayElements?: OverlayConfig;

    // TTS URLs generated by backend
    ttsTemplateUrl?: string;
    ttsTemplateVolume?: number;
    ttsUserMessageUrl?: string;
    ttsUserMessageVolume?: number;

    // Legacy alertConfig (backward compatibility)
    alertConfig?: {
        duration?: number;
        sound?: {
            url?: string;
            volume?: number;
        };
        animation?: {
            type?: string;
            duration?: number;
        };
        style?: {
            backgroundColor?: string;
            textColor?: string;
            accentColor?: string;
            fontSize?: number;
            fontFamily?: string;
        };
        media?: MediaConfig | {
            imageUrl?: string;
            videoUrl?: string;
        };
        playVideoAudio?: boolean;
        videoVolume?: number;
        overlay?: OverlayConfig;
    };
}

interface QueuedTip extends TipAlertData {
    queuedAt: number;
}

// Default positions
const DEFAULT_CARD: OverlayCardConfig = {
    x: 660,
    y: 290,
    width: 600,
    height: 500,
    enabled: true,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    borderRadius: 24,
    borderColor: '#9146FF',
    borderWidth: 0,
    boxShadow: true,
    opacity: 100
};

const DEFAULT_MEDIA: OverlayMediaConfig = {
    id: 'media-1',
    x: 690,
    y: 320,
    width: 540,
    height: 180,
    enabled: true,
    url: '',
    fit: 'contain',
    animationIn: 'zoomIn',
    animationOut: 'fadeOut',
    animationDuration: 500,
    zIndex: 10,
    videoVolume: 80,
    playVideoAudio: false
};

const DEFAULT_TEXTS: OverlayTextConfig[] = [
    {
        id: 'text-1',
        x: 690,
        y: 520,
        width: 540,
        height: 100,
        enabled: true,
        template: '¡{donorName} donó {amount}!',
        fontFamily: 'Inter, sans-serif',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#ffffff',
        textAlign: 'center',
        textShadow: true,
        animationIn: 'slideUp',
        animationOut: 'fadeOut',
        animationDuration: 500,
        zIndex: 20
    },
    {
        id: 'text-2',
        x: 690,
        y: 640,
        width: 540,
        height: 120,
        enabled: true,
        template: '"{message}"',
        fontFamily: 'Inter, sans-serif',
        fontSize: 24,
        fontWeight: 'normal',
        color: '#e0e0e0',
        textAlign: 'center',
        textShadow: false,
        animationIn: 'fadeIn',
        animationOut: 'fadeOut',
        animationDuration: 500,
        zIndex: 21
    }
];

export default function TipsOverlay() {
    const [searchParams] = useSearchParams();
    const channelName = searchParams.get('channel') || '';
    const debugMode = searchParams.get('debug') === 'true';

    const [currentTip, setCurrentTip] = useState<TipAlertData | null>(null);
    const [isVisible, setIsVisible] = useState(false);
    const [queueCount, setQueueCount] = useState(0);

    const connectionRef = useRef<signalR.HubConnection | null>(null);
    const videoRef = useRef<HTMLVideoElement | null>(null);
    const tipQueueRef = useRef<QueuedTip[]>([]);
    const isProcessingRef = useRef(false);
    const enqueueTipRef = useRef<(data: TipAlertData) => void>(() => {});

    // Audio - AudioContext for OBS compatibility (same as EventAlertsOverlay)
    const audioContextRef = useRef<AudioContext | null>(null);
    const audioSourceRef = useRef<AudioBufferSourceNode | null>(null);
    // alertId: incremental counter to cancel stale audio sequences
    const alertIdRef = useRef(0);

    // Queue settings
    const MAX_QUEUE_SIZE = 20;
    const DELAY_BETWEEN_TIPS = 1500;

    // Canvas dimensions (1920x1080 reference)
    const CANVAS_WIDTH = 1920;
    const CANVAS_HEIGHT = 1080;

    // Initialize AudioContext (unlocks autoplay in OBS Browser Source)
    useEffect(() => {
        const ctx = new AudioContext();
        audioContextRef.current = ctx;

        const tryUnlock = async () => {
            if (ctx.state === 'suspended') await ctx.resume();
            if (ctx.state === 'running') console.log('[TipsOverlay] AudioContext desbloqueado');
        };
        tryUnlock().catch(() => {});

        const unlock = () => { tryUnlock().catch(() => {}); };
        document.addEventListener('click', unlock);
        document.addEventListener('keydown', unlock);

        return () => {
            document.removeEventListener('click', unlock);
            document.removeEventListener('keydown', unlock);
            ctx.close();
        };
    }, []);

    // Process queue
    const processQueue = useCallback(async () => {
        if (isProcessingRef.current || tipQueueRef.current.length === 0) {
            return;
        }

        isProcessingRef.current = true;
        setQueueCount(tipQueueRef.current.length);

        while (tipQueueRef.current.length > 0) {
            const tip = tipQueueRef.current.shift()!;
            setQueueCount(tipQueueRef.current.length);

            await showTipAlert(tip);

            // Delay between tips
            if (tipQueueRef.current.length > 0) {
                await new Promise(resolve => setTimeout(resolve, DELAY_BETWEEN_TIPS));
            }
        }

        isProcessingRef.current = false;
        setQueueCount(0);
    }, []);

    // Stop all audio immediately
    const stopAllAudio = () => {
        if (audioSourceRef.current) {
            try { audioSourceRef.current.stop(); } catch {}
            audioSourceRef.current = null;
        }
    };

    // Play one audio URL via AudioContext (OBS-compatible) with HTMLAudioElement fallback
    const playAudio = async (url: string, volume: number): Promise<void> => {
        const ctx = audioContextRef.current;
        if (ctx) {
            try {
                if (ctx.state === 'suspended') await ctx.resume();
                const response = await fetch(url);
                if (!response.ok) throw new Error(`HTTP ${response.status}`);
                const arrayBuffer = await response.arrayBuffer();
                const audioBuffer = await ctx.decodeAudioData(arrayBuffer);
                const source = ctx.createBufferSource();
                const gain = ctx.createGain();
                gain.gain.value = Math.max(0, Math.min(1, volume / 100));
                source.buffer = audioBuffer;
                source.connect(gain);
                gain.connect(ctx.destination);
                audioSourceRef.current = source;
                return new Promise<void>((resolve) => {
                    source.onended = () => resolve();
                    source.start(0);
                });
            } catch (err) {
                console.error('[TipsOverlay] AudioContext error, falling back:', err);
            }
        }
        // Fallback: HTMLAudioElement
        return new Promise<void>((resolve) => {
            const audio = new Audio(url);
            audio.volume = Math.max(0, Math.min(1, volume / 100));
            audio.onended = () => resolve();
            audio.onerror = () => resolve();
            audio.play().catch(() => resolve());
        });
    };

    // Wait for the video element to play through one cycle (for synchronized video audio)
    const waitForVideoAudio = async (volume: number): Promise<void> => {
        let video = videoRef.current;
        let attempts = 0;
        while (!video && attempts < 20) {
            await new Promise(r => setTimeout(r, 100));
            video = videoRef.current;
            attempts++;
        }
        if (!video) return;

        // Wait for metadata if not loaded
        if (!video.duration || !isFinite(video.duration)) {
            await new Promise<void>((resolve) => {
                const onLoaded = () => { video!.removeEventListener('loadedmetadata', onLoaded); resolve(); };
                video!.addEventListener('loadedmetadata', onLoaded);
                setTimeout(resolve, 3000); // safety timeout
            });
        }

        return new Promise<void>((resolve) => {
            video!.muted = false;
            video!.volume = Math.max(0, Math.min(1, volume / 100));
            const remaining = Math.max((video!.duration - video!.currentTime), 0.5) * 1000;
            console.log('[TipsOverlay] [2/4] Video audio for', (remaining / 1000).toFixed(1), 's');
            setTimeout(() => {
                if (videoRef.current) videoRef.current.muted = true;
                resolve();
            }, remaining);
        });
    };

    /**
     * Strict audio hierarchy (sequential, never simultaneous):
     *   [1/4] soundUrl         → alert sound effect
     *   [2/4] video audio      → if playVideoAudio=true and mediaType=video
     *   [3/4] ttsTemplateUrl   → TTS of configured message template
     *   [4/4] ttsUserMessageUrl → TTS of donor's custom message
     *
     * Each step checks alertId so a new tip cancels any stale sequence.
     * Duration is the MINIMUM visible time — audio extends it if needed.
     */
    const playAudioSequence = async (tip: TipAlertData, alertId: number): Promise<void> => {
        // [1/4] Alert sound
        const soundUrl = tip.soundUrl || tip.alertConfig?.sound?.url;
        const soundVolume = tip.soundVolume ?? tip.alertConfig?.sound?.volume ?? 80;
        if (soundUrl && alertIdRef.current === alertId) {
            console.log('[TipsOverlay] [1/4] Sound:', soundUrl, 'vol:', soundVolume);
            await playAudio(soundUrl, soundVolume);
            console.log('[TipsOverlay] [1/4] Sound terminado');
        }

        // [2/4] Video audio
        const shouldPlayVideoAudio = tip.playVideoAudio ?? tip.alertConfig?.playVideoAudio ?? false;
        const videoVol = tip.videoVolume ?? tip.alertConfig?.videoVolume ?? 80;
        if (shouldPlayVideoAudio && tip.mediaType === 'video' && alertIdRef.current === alertId) {
            console.log('[TipsOverlay] [2/4] Video audio...');
            await waitForVideoAudio(videoVol);
            console.log('[TipsOverlay] [2/4] Video audio terminado');
        }

        // [3/4] TTS template
        if (tip.ttsTemplateUrl && alertIdRef.current === alertId) {
            console.log('[TipsOverlay] [3/4] TTS template:', tip.ttsTemplateUrl);
            await playAudio(tip.ttsTemplateUrl, tip.ttsTemplateVolume ?? 80);
            console.log('[TipsOverlay] [3/4] TTS template terminado');
        }

        // [4/4] TTS user message
        if (tip.ttsUserMessageUrl && alertIdRef.current === alertId) {
            console.log('[TipsOverlay] [4/4] TTS message:', tip.ttsUserMessageUrl);
            await playAudio(tip.ttsUserMessageUrl, tip.ttsUserMessageVolume ?? 80);
            console.log('[TipsOverlay] [4/4] TTS message terminado');
        }
    };

    // Show a single tip alert.
    // duration = minimum visible time; audio sequence runs to completion first,
    // then the remaining time (if any) is waited before hiding.
    const showTipAlert = async (tip: TipAlertData): Promise<void> => {
        const myId = ++alertIdRef.current;

        // Duration in ms — minimum time the overlay stays visible
        const duration = tip.duration
            ?? tip.alertConfig?.overlay?.duration
            ?? ((tip.alertConfig?.duration ?? 5) * 1000);

        const startTime = Date.now();

        setCurrentTip(tip);
        setIsVisible(true);

        console.log('[TipsOverlay] Alert #' + myId + ' started, minDuration=' + duration + 'ms');

        // AWAIT the full audio sequence — TTS will never be cut off
        await playAudioSequence(tip, myId);

        // Wait any remaining minimum display time
        const elapsed = Date.now() - startTime;
        const remaining = duration - elapsed;
        if (remaining > 0) {
            await new Promise(r => setTimeout(r, remaining));
        }

        // Hide with exit animation
        setIsVisible(false);
        stopAllAudio();

        await new Promise(r => setTimeout(r, 500)); // animation out

        setCurrentTip(null);
        console.log('[TipsOverlay] Alert #' + myId + ' completed');
    };

    // Enqueue a tip
    const enqueueTip = useCallback((data: TipAlertData) => {
        // Limit queue size
        if (tipQueueRef.current.length >= MAX_QUEUE_SIZE) {
            console.warn('[TipsOverlay] Queue full, dropping oldest tip');
            tipQueueRef.current.shift();
        }

        tipQueueRef.current.push({
            ...data,
            queuedAt: Date.now()
        });

        setQueueCount(tipQueueRef.current.length);

        // Start processing if not already
        if (!isProcessingRef.current) {
            processQueue();
        }
    }, [processQueue]);

    // Keep ref updated
    useEffect(() => {
        enqueueTipRef.current = enqueueTip;
    }, [enqueueTip]);

    // SignalR connection
    useEffect(() => {
        if (!channelName) return;

        let stopped = false;
        let reconnectTimeout: ReturnType<typeof setTimeout> | null = null;

        const setupSignalRConnection = async () => {
            if (stopped) return;

            const connection = new signalR.HubConnectionBuilder()
                .withUrl('/hubs/overlay')
                .withAutomaticReconnect([0, 2000, 5000, 10000, 20000, 30000])
                .configureLogging(signalR.LogLevel.None)
                .build();

            // Handle tip alerts
            connection.on('ShowTipAlert', (data: TipAlertData) => {
                console.log('[TipsOverlay] Received tip:', data);
                console.log('[TipsOverlay] Alert Config:', JSON.stringify(data.alertConfig, null, 2));
                console.log('[TipsOverlay] Overlay Config:', JSON.stringify(data.alertConfig?.overlay, null, 2));
                enqueueTipRef.current(data);
            });

            // Handle config changes
            connection.on('TipsConfigChanged', () => {
                console.log('[TipsOverlay] Config changed');
            });

            // Connection lifecycle - reconnect to channel after automatic reconnection
            connection.onreconnected(async () => {
                try {
                    await connection.invoke('JoinChannel', channelName);
                } catch (err) {
                    console.error('[TipsOverlay] Error re-uniéndose al canal:', err);
                }
            });

            // If connection closes completely, try to reconnect after 5 seconds
            connection.onclose((error) => {
                if (stopped) return;
                reconnectTimeout = setTimeout(setupSignalRConnection, 5000);
            });

            try {
                await connection.start();
                if (stopped) {
                    connection.stop();
                    return;
                }
                await connection.invoke('JoinChannel', channelName);
                connectionRef.current = connection;
            } catch (err) {
                if (!stopped) {
                    reconnectTimeout = setTimeout(setupSignalRConnection, 5000);
                }
            }
        };

        setupSignalRConnection();

        return () => {
            stopped = true;
            if (reconnectTimeout) clearTimeout(reconnectTimeout);
            // Clear queue
            tipQueueRef.current = [];
            isProcessingRef.current = false;
            setQueueCount(0);
            // Stop audio
            stopAllAudio();
            connectionRef.current?.stop();
        };
    }, [channelName]);

    // Replace variables in text template
    const processTemplate = (template: string, tip: TipAlertData): string => {
        return template
            .replace(/{donorName}/g, tip.donorName)
            .replace(/{amount}/g, tip.formattedAmount)
            .replace(/{message}/g, tip.message || '')
            .replace(/{time}/g, tip.timeAdded > 0 ? `+${Math.floor(tip.timeAdded / 60)}m ${tip.timeAdded % 60}s` : '')
            .replace(/{currency}/g, tip.currency);
    };

    // Get animation class based on animation type
    const getAnimationClass = (animationType: string, isEntry: boolean): string => {
        const animMap: Record<string, { in: string; out: string }> = {
            fadeIn: { in: 'animate-fadeIn', out: 'animate-fadeOut' },
            fadeOut: { in: 'animate-fadeIn', out: 'animate-fadeOut' },
            slideUp: { in: 'animate-slideUpIn', out: 'animate-slideUpOut' },
            slideDown: { in: 'animate-slideDownIn', out: 'animate-slideDownOut' },
            slideLeft: { in: 'animate-slideLeftIn', out: 'animate-slideLeftOut' },
            slideRight: { in: 'animate-slideRightIn', out: 'animate-slideRightOut' },
            zoomIn: { in: 'animate-zoomIn', out: 'animate-zoomOut' },
            zoomOut: { in: 'animate-zoomIn', out: 'animate-zoomOut' },
            bounceIn: { in: 'animate-bounceIn', out: 'animate-bounceOut' },
            bounceOut: { in: 'animate-bounceIn', out: 'animate-bounceOut' },
            rotateIn: { in: 'animate-rotateIn', out: 'animate-rotateOut' },
            rotateOut: { in: 'animate-rotateIn', out: 'animate-rotateOut' },
            none: { in: '', out: '' }
        };
        const anim = animMap[animationType] || animMap.fadeIn;
        return isEntry ? anim.in : anim.out;
    };

    // Legacy animation for fallback — use flat animationIn/Out or derive from animation.type
    const getLegacyAnimationClass = () => {
        if (!isVisible) {
            if (currentTip?.animationOut) return `animate-${currentTip.animationOut}`;
            const animType = currentTip?.alertConfig?.animation?.type || 'fade';
            return animType === 'slide' ? 'animate-slideOut' :
                   animType === 'bounce' ? 'animate-bounceOut' :
                   animType === 'zoom' ? 'animate-zoomOut' :
                   'animate-fadeOut';
        }
        if (currentTip?.animationIn) return `animate-${currentTip.animationIn}`;
        const animType = currentTip?.alertConfig?.animation?.type || 'fade';
        return animType === 'slide' ? 'animate-slideIn' :
               animType === 'bounce' ? 'animate-bounceIn' :
               animType === 'zoom' ? 'animate-zoomIn' :
               'animate-fadeIn';
    };

    if (!channelName) {
        return (
            <div className="w-screen h-screen flex items-center justify-center bg-black text-white">
                <p>Missing channel parameter. Use ?channel=YOUR_CHANNEL</p>
            </div>
        );
    }

    // Get overlay config with defaults — supports flat overlayElements or legacy alertConfig.overlay
    const getOverlayConfig = (): OverlayConfig => {
        const config = currentTip?.overlayElements || currentTip?.alertConfig?.overlay;
        return {
            canvas: config?.canvas || { width: CANVAS_WIDTH, height: CANVAS_HEIGHT },
            card: config?.card || DEFAULT_CARD,
            media: config?.media || DEFAULT_MEDIA,
            texts: config?.texts || DEFAULT_TEXTS,
            duration: config?.duration || currentTip?.duration || 5000,
            animationIn: config?.animationIn || currentTip?.animationIn || 'bounceIn',
            animationOut: config?.animationOut || currentTip?.animationOut || 'fadeOut'
        };
    };

    // Check if we have overlay config (use new renderer) or fallback to legacy
    const hasOverlayConfig = currentTip?.overlayElements || currentTip?.alertConfig?.overlay;

    return (
        <div className="w-screen h-screen overflow-hidden relative" style={{ background: 'transparent' }}>
            {/* Debug info */}
            {debugMode && (
                <div className="absolute top-2 left-2 bg-black/80 text-white text-xs p-2 rounded z-50">
                    <div>Channel: {channelName}</div>
                    <div>Queue: {queueCount}</div>
                    <div>Processing: {isProcessingRef.current ? 'Yes' : 'No'}</div>
                    <div>Has Overlay Config: {hasOverlayConfig ? 'Yes' : 'No'}</div>
                </div>
            )}

            {/* Queue counter */}
            {queueCount > 0 && (
                <div className="absolute top-2 right-2 bg-purple-600 text-white text-sm px-3 py-1 rounded-full z-50">
                    {queueCount} in queue
                </div>
            )}

            {/* Tip Alert - New Overlay System */}
            {currentTip && hasOverlayConfig && (() => {
                const overlayConfig = getOverlayConfig();
                const card = overlayConfig.card!;
                const media = overlayConfig.media!;
                const texts = overlayConfig.texts!;

                return (
                    <div
                        className={`absolute inset-0 ${isVisible ? getAnimationClass(overlayConfig.animationIn || 'bounceIn', true) : getAnimationClass(overlayConfig.animationOut || 'fadeOut', false)}`}
                        style={{ width: '100%', height: '100%' }}
                    >
                        {/* Card/Background */}
                        {card.enabled && (
                            <div
                                className="absolute"
                                style={{
                                    left: `${(card.x / CANVAS_WIDTH) * 100}%`,
                                    top: `${(card.y / CANVAS_HEIGHT) * 100}%`,
                                    width: `${(card.width / CANVAS_WIDTH) * 100}%`,
                                    height: `${(card.height / CANVAS_HEIGHT) * 100}%`,
                                    backgroundColor: card.backgroundColor,
                                    borderRadius: `${card.borderRadius}px`,
                                    border: card.borderWidth > 0 ? `${card.borderWidth}px solid ${card.borderColor}` : 'none',
                                    boxShadow: card.boxShadow ? '0 25px 50px -12px rgba(0, 0, 0, 0.5)' : 'none',
                                    opacity: card.opacity / 100
                                }}
                            />
                        )}

                        {/* Media - supports flat fields, advanced config, and legacy overlay config */}
                        {media.enabled && (() => {
                            // Flat fields take priority, then advanced media config, then overlay config URL
                            const advancedMedia = (currentTip.alertConfig?.media as MediaConfig)?.mode === 'advanced'
                                ? (currentTip.alertConfig?.media as MediaConfig).advanced
                                : undefined;

                            const resolvedMediaUrl = currentTip.mediaUrl || advancedMedia?.video?.url || advancedMedia?.image?.url || media.url;
                            const mediaUrl = resolvedMediaUrl;

                            // Determine if video audio should play — flat fields take priority
                            const playVideoAudio = currentTip.playVideoAudio ?? currentTip.alertConfig?.playVideoAudio ?? media.playVideoAudio ?? false;
                            const videoVolume = ((currentTip.videoVolume ?? currentTip.alertConfig?.videoVolume ?? advancedMedia?.video?.volume ?? media.videoVolume ?? 80)) / 100;

                            if (!mediaUrl) return null;

                            const isVideo = /\.(mp4|webm|mov)$/i.test(mediaUrl);

                            return (
                                <div
                                    className={`absolute overflow-hidden ${isVisible ? getAnimationClass(media.animationIn, true) : getAnimationClass(media.animationOut, false)}`}
                                    style={{
                                        left: `${(media.x / CANVAS_WIDTH) * 100}%`,
                                        top: `${(media.y / CANVAS_HEIGHT) * 100}%`,
                                        width: `${(media.width / CANVAS_WIDTH) * 100}%`,
                                        height: `${(media.height / CANVAS_HEIGHT) * 100}%`,
                                        zIndex: media.zIndex,
                                        animationDuration: `${media.animationDuration}ms`
                                    }}
                                >
                                    {isVideo ? (
                                        <video
                                            ref={videoRef}
                                            src={mediaUrl}
                                            autoPlay
                                            loop={advancedMedia?.video?.loop ?? true}
                                            muted={!playVideoAudio}
                                            className="w-full h-full"
                                            style={{ objectFit: media.fit }}
                                            onLoadedMetadata={(e) => {
                                                if (playVideoAudio) {
                                                    (e.target as HTMLVideoElement).volume = videoVolume;
                                                }
                                            }}
                                        />
                                    ) : (
                                        <img
                                            src={mediaUrl}
                                            alt=""
                                            className="w-full h-full"
                                            style={{ objectFit: media.fit }}
                                        />
                                    )}
                                </div>
                            );
                        })()}

                        {/* Texts */}
                        {texts.map((text) => {
                            if (!text.enabled) return null;
                            const processedText = processTemplate(text.template, currentTip);

                            // Skip empty messages
                            if (text.template.includes('{message}') && !currentTip.message) {
                                return null;
                            }

                            return (
                                <div
                                    key={text.id}
                                    className={`absolute flex items-center justify-center ${isVisible ? getAnimationClass(text.animationIn, true) : getAnimationClass(text.animationOut, false)}`}
                                    style={{
                                        left: `${(text.x / CANVAS_WIDTH) * 100}%`,
                                        top: `${(text.y / CANVAS_HEIGHT) * 100}%`,
                                        width: `${(text.width / CANVAS_WIDTH) * 100}%`,
                                        height: `${(text.height / CANVAS_HEIGHT) * 100}%`,
                                        fontFamily: text.fontFamily,
                                        fontSize: `${text.fontSize}px`,
                                        fontWeight: text.fontWeight,
                                        color: text.color,
                                        textAlign: text.textAlign,
                                        textShadow: text.textShadow ? '2px 2px 4px rgba(0,0,0,0.8)' : 'none',
                                        zIndex: text.zIndex,
                                        animationDuration: `${text.animationDuration}ms`
                                    }}
                                >
                                    <div className="w-full text-center break-words">
                                        {processedText}
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                );
            })()}

            {/* Legacy Tip Alert - Fallback when no overlay config */}
            {currentTip && !hasOverlayConfig && (
                <div
                    className={`absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 ${getLegacyAnimationClass()}`}
                    style={{
                        backgroundColor: currentTip.alertConfig?.style?.backgroundColor || 'rgba(0, 0, 0, 0.9)',
                        color: currentTip.alertConfig?.style?.textColor || '#ffffff',
                        fontFamily: currentTip.alertConfig?.style?.fontFamily || 'Inter, sans-serif'
                    }}
                >
                    <div className="flex flex-col items-center p-8 rounded-2xl shadow-2xl min-w-[400px] max-w-[600px]"
                         style={{ backgroundColor: currentTip.alertConfig?.style?.backgroundColor || 'rgba(0,0,0,0.9)' }}>

                        {/* Media (image/video) */}
                        {currentTip.alertConfig?.media?.imageUrl && (
                            <img
                                src={currentTip.alertConfig.media.imageUrl}
                                alt="Tip"
                                className="w-32 h-32 object-contain mb-4"
                            />
                        )}
                        {currentTip.alertConfig?.media?.videoUrl && (
                            <video
                                src={currentTip.alertConfig.media.videoUrl}
                                autoPlay
                                loop
                                muted
                                className="w-48 h-32 object-contain mb-4"
                            />
                        )}

                        {/* Amount */}
                        <div
                            className="text-5xl font-black mb-2"
                            style={{ color: currentTip.alertConfig?.style?.accentColor || '#9146FF' }}
                        >
                            {currentTip.formattedAmount}
                        </div>

                        {/* Donor name */}
                        <div className="text-2xl font-bold mb-2">
                            {currentTip.donorName}
                        </div>

                        {/* Message */}
                        {currentTip.message && (
                            <div className="text-lg text-center opacity-90 max-w-[500px] break-words">
                                "{currentTip.message}"
                            </div>
                        )}

                        {/* Time added */}
                        {currentTip.timeAdded > 0 && (
                            <div className="mt-4 text-sm opacity-70">
                                +{Math.floor(currentTip.timeAdded / 60)}m {currentTip.timeAdded % 60}s added to timer
                            </div>
                        )}
                    </div>
                </div>
            )}

            {/* CSS Animations */}
            <style>{`
                @keyframes fadeIn {
                    from { opacity: 0; }
                    to { opacity: 1; }
                }
                @keyframes fadeOut {
                    from { opacity: 1; }
                    to { opacity: 0; }
                }
                @keyframes slideIn {
                    from { opacity: 0; transform: translate(-50%, -100%); }
                    to { opacity: 1; transform: translate(-50%, -50%); }
                }
                @keyframes slideOut {
                    from { opacity: 1; transform: translate(-50%, -50%); }
                    to { opacity: 0; transform: translate(-50%, 100%); }
                }
                @keyframes slideUpIn {
                    from { opacity: 0; transform: translateY(50px); }
                    to { opacity: 1; transform: translateY(0); }
                }
                @keyframes slideUpOut {
                    from { opacity: 1; transform: translateY(0); }
                    to { opacity: 0; transform: translateY(-50px); }
                }
                @keyframes slideDownIn {
                    from { opacity: 0; transform: translateY(-50px); }
                    to { opacity: 1; transform: translateY(0); }
                }
                @keyframes slideDownOut {
                    from { opacity: 1; transform: translateY(0); }
                    to { opacity: 0; transform: translateY(50px); }
                }
                @keyframes slideLeftIn {
                    from { opacity: 0; transform: translateX(50px); }
                    to { opacity: 1; transform: translateX(0); }
                }
                @keyframes slideLeftOut {
                    from { opacity: 1; transform: translateX(0); }
                    to { opacity: 0; transform: translateX(-50px); }
                }
                @keyframes slideRightIn {
                    from { opacity: 0; transform: translateX(-50px); }
                    to { opacity: 1; transform: translateX(0); }
                }
                @keyframes slideRightOut {
                    from { opacity: 1; transform: translateX(0); }
                    to { opacity: 0; transform: translateX(50px); }
                }
                @keyframes bounceIn {
                    0% { opacity: 0; transform: scale(0.3); }
                    50% { transform: scale(1.1); }
                    70% { transform: scale(0.9); }
                    100% { opacity: 1; transform: scale(1); }
                }
                @keyframes bounceOut {
                    0% { opacity: 1; transform: scale(1); }
                    100% { opacity: 0; transform: scale(0.3); }
                }
                @keyframes zoomIn {
                    from { opacity: 0; transform: scale(0); }
                    to { opacity: 1; transform: scale(1); }
                }
                @keyframes zoomOut {
                    from { opacity: 1; transform: scale(1); }
                    to { opacity: 0; transform: scale(0); }
                }
                @keyframes rotateIn {
                    from { opacity: 0; transform: rotate(-180deg) scale(0); }
                    to { opacity: 1; transform: rotate(0) scale(1); }
                }
                @keyframes rotateOut {
                    from { opacity: 1; transform: rotate(0) scale(1); }
                    to { opacity: 0; transform: rotate(180deg) scale(0); }
                }
                .animate-fadeIn { animation: fadeIn 0.5s ease-out forwards; }
                .animate-fadeOut { animation: fadeOut 0.5s ease-out forwards; }
                .animate-slideIn { animation: slideIn 0.5s ease-out forwards; }
                .animate-slideOut { animation: slideOut 0.5s ease-out forwards; }
                .animate-slideUpIn { animation: slideUpIn 0.5s ease-out forwards; }
                .animate-slideUpOut { animation: slideUpOut 0.5s ease-out forwards; }
                .animate-slideDownIn { animation: slideDownIn 0.5s ease-out forwards; }
                .animate-slideDownOut { animation: slideDownOut 0.5s ease-out forwards; }
                .animate-slideLeftIn { animation: slideLeftIn 0.5s ease-out forwards; }
                .animate-slideLeftOut { animation: slideLeftOut 0.5s ease-out forwards; }
                .animate-slideRightIn { animation: slideRightIn 0.5s ease-out forwards; }
                .animate-slideRightOut { animation: slideRightOut 0.5s ease-out forwards; }
                .animate-bounceIn { animation: bounceIn 0.6s ease-out forwards; }
                .animate-bounceOut { animation: bounceOut 0.4s ease-out forwards; }
                .animate-zoomIn { animation: zoomIn 0.4s ease-out forwards; }
                .animate-zoomOut { animation: zoomOut 0.4s ease-out forwards; }
                .animate-rotateIn { animation: rotateIn 0.5s ease-out forwards; }
                .animate-rotateOut { animation: rotateOut 0.5s ease-out forwards; }
            `}</style>
        </div>
    );
}
