ALTER TABLE sound_alert_files
    ADD COLUMN IF NOT EXISTS show_image BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS image_url VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS image_source VARCHAR(20) NOT NULL DEFAULT 'upload';
